# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.vfs.watch=true

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.enableAppCompileTimeRClass=true

kotlin.code.style=official
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
# kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Safety for Windows established connection aborted
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false


# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# 16 KB Page Alignment support
android.bundle.enable16kPageAlignment=true

# Suppress Kotlin Gradle Plugin deprecated Gradle version warnings
kotlin.suppressGradlePluginWarnings=DeprecatedGradleVersionWarning

